import PostPagination from "@/components/PostPagination";
import PostsLists from "@/components/PostsLists";
import { getPostPagination, totalPages } from "@/utils/PostsPaginationUtil";

export const metadata = {
  title: "Lista de todos los post",
  description: "Description posts - Generated by create next app",
};

const Posts = () => {
  const { currentPosts } = getPostPagination();

  return (
    <>
      <h1 className="text-center my-4 text-3xl">Posts</h1>
      <div className="grid gap-4">
        <PostsLists posts={currentPosts} />
        {totalPages > 1 && <PostPagination totalPages={totalPages} />}
      </div>
    </>
  );
};

export default Posts;
